@startuml
class CommunitySponsor {
   +name : String
   +information : String
   +logo_photo : File
   +type : String
   +industry : String
   +website : String
   #email : String
   #phone : Integer
}
@enduml
